# Generated by Django 4.2.10 on 2024-02-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
